# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='eventpics/')),
                ('rate', models.IntegerField()),
                ('booked_date', models.DateField()),
                ('event_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
