# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20180808_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='booked_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myevent',
            name='event_type',
            field=models.CharField(choices=[('WEDDING', 'WEDDING'), ('PHOTOGRAPHY', 'PHOTOGRAPHY'), ('VIDEOGRAPHY', 'VIDEOGRAPHY'), ('DECORATION', 'DECORATION')], max_length=100),
        ),
    ]
