# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20180808_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
