# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_auto_20180808_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/eventpics/'),
        ),
    ]
