# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_auto_20180808_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevent',
            old_name='booked_date',
            new_name='booking_date',
        ),
    ]
