# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_auto_20180809_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='address',
        ),
    ]
