# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_auto_20180809_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='event_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='event_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
