# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_auto_20180809_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='booked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
